### ISSUE TITLE
Publish TypeParameterResolver for computing method return type, arguments, field types with account of actual type arguments

### ISSUE THREAD

**Issue by vlsi** [harawata/typeparameterresolver#1]
See https://github.com/mybatis/mybatis-3/issues/2746

**Comment by harawata** [comment]
Is 1.0.0-SNAPSHOT working fine for you?
If you think it's ready, I can deploy 1.0.0 to the central right away.

**Comment by vlsi** [comment]
1.0.0-SNAPSHOT works for me

**Comment by harawata** [comment]
1.0.0 is published on the maven central.
Thanks for the README as well!

**Comment by harawata** [comment]
FYI, I didn't test it, but this one seems to have a similar API (and more).
https://github.com/leangen/geantyref

[EDIT]
I just did a quick test and it does not seem to work as I expected.
